# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'krosconApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
